general:
  # WM 시작 시 실행할 명령어. 스크립트 실행이나 다른 애플리케이션을 시작하는 데 유용합니다.
  # 예시: 아래 명령어는 Zebar를 실행합니다.
  startup_commands: ['shell-exec zebar']

  # WM 종료 직전에 실행할 명령어.
  # 예시: 아래 명령어는 Zebar를 종료합니다.
  shutdown_commands: ['shell-exec taskkill /IM zebar.exe /F']

  # WM 설정이 재로드된 후 실행할 명령어.
  config_reload_commands: []
  
  # 커서 아래에 있는 창을 자동으로 포커스할지 여부.
  focus_follows_cursor: false

  # 현재 작업 공간에 포커스할 때 이전에 포커스했던 작업 공간으로 다시 전환할지 여부.
  toggle_workspace_on_refocus: false

  cursor_jump:
    # 지정된 트리거에서 커서를 자동으로 이동할지 여부.
    enabled: true

    # 커서 점프 트리거:
    # - 'monitor_focus': 모니터 간 포커스 변경 시 점프.
    # - 'window_focus': 창 간 포커스 변경 시 점프.
    trigger: 'window_focus'

  # 작업 공간 전환 시 창을 숨기는 방법.
  # - 'cloak': 권장. 애니메이션 없이 창을 숨깁니다.
  # - 'hide': 레거시 방식 (v3.5 이하). 짧은 애니메이션이 있지만 일부 앱에서 안정성 문제가 있습니다.
  hide_method: 'cloak'

  # 네이티브 Windows 작업 표시줄에 표시될 창에 영향을 줍니다. `hide_method: 'hide'`인 경우 효과가 없습니다.
  # - 'true': 모든 창 표시 (작업 공간에 관계없이).
  # - 'false': 현재 표시된 작업 공간의 창만 표시.
  show_all_in_taskbar: false

gaps:
  # 갭을 모니터 DPI에 따라 조정할지 여부.
  scale_with_dpi: true

  # 인접한 창 사이의 갭.
  inner_gap: '15px'

  # 창과 화면 가장자리 사이의 갭.
  outer_gap:
    top: '50px'
    right: '15px'
    bottom: '15px'
    left: '15px'

window_effects:
  # 포커스된 창에 적용할 시각 효과.
  focused_window:
    # 색상 테두리로 창을 강조 표시합니다.
    # ** API 제한으로 인해 Windows 11 전용입니다.
    border:
      enabled: false
      color: '#8dbcff'

    # 창 프레임에서 제목 표시줄을 제거합니다. 일부 애플리케이션에서 렌더링 문제가 발생할 수 있습니다.
    hide_title_bar:
      enabled: false

    # 창 프레임의 모서리 스타일을 변경합니다.
    # ** API 제한으로 인해 Windows 11 전용입니다.
    corner_style:
      enabled: false
      # 허용되는 값: 'square', 'rounded', 'small_rounded'.
      style: 'square'

    # 창의 투명도를 변경합니다.
    transparency:
      enabled: false
      # 약간 투명한 창을 위해 '95%' 또는 '0.95'와 같이 사용할 수 있습니다.
      # '0' 또는 '0%'는 완전히 투명합니다 (따라서 포커스할 수 없습니다).
      opacity: '100%'

  # 포커스되지 않은 창에 적용할 시각 효과.
  other_windows:
    border:
      enabled: false
      color: '#a1a1a1'
    hide_title_bar:
      enabled: false
    corner_style:
      enabled: false
      style: 'square'
    transparency:
      enabled: true
      opacity: '85%'

window_behavior:
  # 새 창이 생성될 때 가능한 경우 이 상태로 생성됩니다.
  # 허용되는 값: 'tiling', 'floating'.
  initial_state: 'tiling'

  # 새 창이 생성될 때 기본 옵션을 설정합니다. 또한 `set-floating`과 같은 상태 변경 명령이 플래그 없이 사용될 때 기본값을 변경합니다.
  state_defaults:
    floating:
      # 플로팅 창을 기본적으로 가운데 정렬할지 여부.
      centered: false

      # 플로팅 창을 항상 맨 위에 표시할지 여부.
      shown_on_top: false

    fullscreen:
      # 가능한 경우 창을 최대화합니다. 창에 최대화 버튼이 없으면 대신 일반적인 전체 화면으로 표시됩니다.
      maximized: true

      # 전체 화면 창을 항상 맨 위에 표시할지 여부.
      shown_on_top: false

workspaces:
  - name: 'B' # 브라우저용
    display_name: "Browser"
    bind_to_monitor: 2
  - name: 'D' # 문서용
    display_name: "Document"
    bind_to_monitor: 2
  - name: 'F' # 탐색기용
    display_name: "File Explorer"
    bind_to_monitor: 2
  - name: 'I' # IDE용
    display_name: "IDE"
    bind_to_monitor: 2
  - name: 'M' # 메신저용
    display_name: "Messenger"
    bind_to_monitor: 1
  - name: 'N' # 노트용
    display_name: "Notes"
    bind_to_monitor: 2
  - name: 'T' # 터미널용
    display_name: "Terminal"
    bind_to_monitor: 1
  - name: 'Z' # 기타
    bind_to_monitor: 2

window_rules:
  - commands: ['ignore']
    match:
      # 모든 Zebar 창 무시.
      - window_process: { equals: 'zebar' }

      # 브라우저의 PIP (Picture-in-Picture) 창 무시.
      - window_title: { regex: '[Pp]icture.in.[Pp]icture' }
        window_class: { regex: 'Chrome_WidgetWin_1|MozillaDialogClass' }

      # 다양한 타사 앱에 대한 무시 규칙.
      - window_process: { equals: 'PowerToys' }
        window_class: { regex: 'HwndWrapper\[PowerToys\.PowerAccent.*?\]' }
      - window_process: { equals: 'PowerToys' }
        window_title: { regex: '.*? - Peek' }
      - window_process: { equals: 'Lively' }
        window_class: { regex: 'HwndWrapper' }
      - window_title: { regex: '명령 도구 모음' }
      # Windows 10 시스템 UI 요소 무시
      - window_class: { equals: 'Windows.UI.Core.CoreWindow' }
      - window_class: { equals: 'ApplicationFrameWindow' }
        window_title: { regex: 'Settings|Microsoft Store' }
      # 파일 탐색기 특수 창 무시 (파일 선택 대화 상자, 속성 창 등)
      - window_process: { equals: 'explorer' }
        window_title: { regex: '열기|저장|다른 이름으로 저장|속성|Properties|Open|Save|Save As' }

      # 카카오톡 알림창 무시
      - window_process: { equals: 'KakaoTalk' }
        # window_title: { regex: '알림|Notification|새 메시지|New message' }

      # 슬랙 알림창 무시
      - window_process: { equals: 'Slack' }
        window_title: { regex: 'Notification|알림|Slack Notification' }

  - commands: ["set-floating"]
    match:
      - window_process: { equals: 'Taskmgr' }
      - window_process: { equals: "explorer" }
        window_title: { regex: 'Properties|설정|속성|제어판' }
      - window_title: { regex: 'Settings|설정' }
      - window_title: { regex: 'DevToys' }
      - window_title: { regex: '스티커 메모' }
      - window_process: { equals: 'EXCEL' }
      - window_process: { equals: 'WINWORD' }
      - window_process: { equals: 'POWERPNT' }

  # 작업 공간에 창 자동 할당
  - commands: ['move --workspace T', 'focus --workspace T']
    match:
      - window_process: { equals: 'WindowsTerminal' }
      - window_process: { equals: 'cmd' }
      - window_process: { equals: 'powershell' }
      - window_process: { equals: 'wt' }

  - commands: ['move --workspace B', 'focus --workspace B']
    match:
      - window_process: { equals: 'chrome' }
      # - window_process: { equals: 'msedge' }
      - window_process: { equals: 'zen' }
      # - window_process: { equals: 'Arc' }

  - commands: ['move --workspace I', 'focus --workspace I']
    match:
      - window_process: { equals: 'idea64' }
      - window_process: { equals: 'Code' }
      - window_process: { equals: 'Cursor' }
      - window_process: { equals: 'Trae' }
      # - window_process: { equals: 'eclipse' }  # Eclipse IDE 추가

  - commands: ['move --workspace N', 'focus --workspace N']
    match:
      - window_process: { equals: 'Obsidian' }

  - commands: ['move --workspace F', 'focus --workspace F']
    match:
      - window_process: { equals: 'explorer' }
        window_title: { not_regex: '열기|저장|다른 이름으로 저장|속성|Properties|Open|Save|Save As' }

  # - commands: ['move --workspace D', 'focus --workspace D']
  #   match:
  #     - window_process: { equals: 'EXCEL' }
  #     - window_process: { equals: 'WINWORD' }
  #     - window_process: { equals: 'POWERPNT' }

  # 메신저 앱 규칙 (플로팅 모드로 설정하고 M 작업 공간으로 이동)
  - commands: ['set-floating', 'move --workspace M']
    match:
      - window_process: { equals: 'Slack' }
        window_title: { not_regex: 'Notification|알림|Slack Notification' }
      - window_process: { equals: 'KakaoTalk' }
        window_title: { not_regex: '알림|Notification|새 메시지|New message' }
      - window_title: { regex: '카카오톡' }
      - window_title: { regex: '휴대폰과 연결'}
      - window_title: { regex: 'SPORKY의 S22'}

  # 지정되지 않은 모든 앱을 Z 작업 공간으로 이동
  # - commands: ['move --workspace Z', 'focus --workspace Z']
  #   match:
  #     # 이미 규칙이 있는 앱들은 제외
  #     - window_process: { not_regex: 'zebar|WindowsTerminal|cmd|powershell|wt|chrome|firefox|Arc|idea64|Code|Cursor|Trae|eclipse|Obsidian|explorer|EXCEL|WINWORD|POWERPNT|Slack|KakaoTalk' }
binding_modes:
  # 활성화되면 포커스된 창의 크기를 화살표 키 또는 HJKL 키로 조정할 수 있습니다.
  - name: 'resize'
    keybindings:
      - commands: ['resize --width -2%']
        bindings: ['h', 'left']
      - commands: ['resize --width +2%']
        bindings: ['l', 'right']
      - commands: ['resize --height +2%']
        bindings: ['k', 'up']
      - commands: ['resize --height -2%']
        bindings: ['j', 'down']
      # 기본 키 바인딩으로 돌아가려면 Enter/Escape 키를 누르세요.
      - commands: ['wm-disable-binding-mode --name resize']
        bindings: ['escape', 'enter']
        
  # 활성화되면 포커스된 창을 화살표 키 또는 HJKL 키로 다른 창과 스왑할 수 있습니다.
  - name: 'swap'
    keybindings:
      - commands: ['move --direction left']
        bindings: ['h', 'left']
      - commands: ['move --direction right']
        bindings: ['l', 'right']
      - commands: ['move --direction up']
        bindings: ['k', 'up']
      - commands: ['move --direction down']
        bindings: ['j', 'down']
      # 기본 키 바인딩으로 돌아가려면 Enter/Escape 키를 누르세요.
      - commands: ['wm-disable-binding-mode --name swap']
        bindings: ['escape', 'enter']
keybindings:
  # 애플리케이션 실행 단축키: 환경변수 PATH의 설정이 추가로 필요.
  # - commands: ['shell-exec Arc']
  #   bindings: ['lalt+lwin+a']
  # - commands: ['shell-exec KakaoTalk']
  #   bindings: ['lalt+lwin+k']
  # - commands: ['shell-exec Slack']
  #   bindings: ['lalt+lwin+s']
  # - commands: ['shell-exec idea64']
  #   bindings: ['lalt+lwin+i']
  # - commands: ['shell-exec Cursor']
  #   bindings: ['lalt+lwin+c']
  # - commands: ['shell-exec Trae']
  #   bindings: ['lalt+lwin+r']
  # - commands: ['shell-exec wt']
  #   bindings: ['lalt+lwin+t']
  # - commands: ['shell-exec Obsidian']
  #   bindings: ['lalt+lwin+o']

  # 주어진 방향으로 포커스 이동.
  - commands: ['focus --direction left']
    bindings: ['alt+h']
  - commands: ['focus --direction right']
    bindings: ['alt+l']
  - commands: ['focus --direction up']
    bindings: ['alt+k']
  - commands: ['focus --direction down']
    bindings: ['alt+j']

  # # 주어진 방향으로 포커스된 창 이동.
  # - commands: ['move --direction left']
  #   bindings: ['alt+shift+h']
  # - commands: ['move --direction right']
  #   bindings: ['alt+shift+l']
  # - commands: ['move --direction up']
  #   bindings: ['alt+shift+k']
  # - commands: ['move --direction down']
  #   bindings: ['alt+shift+j']

  # # 백분율 또는 픽셀 양만큼 포커스된 창 크기 조정.
  # - commands: ['resize --width -2%']
  #   bindings: ['alt+u']
  # - commands: ['resize --width +2%']
  #   bindings: ['alt+p']
  # - commands: ['resize --height +2%']
  #   bindings: ['alt+o']
  # - commands: ['resize --height -2%']
  #   bindings: ['alt+i']

  # 위의 크기 조정 키 바인딩의 대안으로, 크기 조정 모드를 사용하면 화살표 키 또는 HJKL 키로 크기를 조정할 수 있습니다. 바인딩 모드는 위에서 'resize'라는 이름으로 정의되었습니다.
  - commands: ['wm-enable-binding-mode --name resize']
    bindings: ['alt+r']
    
  # 창 스왑 모드를 활성화합니다. 활성화되면 화살표 키 또는 HJKL 키로 창을 스왑할 수 있습니다.
  - commands: ['wm-enable-binding-mode --name swap']
    bindings: ['alt+w']

  # alt+shift+p를 다시 누를 때까지 창 관리 및 다른 모든 키 바인딩을 비활성화합니다.
  - commands: ['wm-toggle-pause']
    bindings: ['alt+shift+p']

  # 타일링 방향 변경. 새 타일링 창이 삽입될 위치를 결정합니다.
  - commands: ['toggle-tiling-direction']
    bindings: ['alt+v']

  # 타일링 창 -> 플로팅 -> 전체 화면으로 포커스 변경.
  # - commands: ['wm-cycle-focus']
  #   bindings: ['alt+space']

  # 포커스된 창을 플로팅으로 변경.
  - commands: ['toggle-floating']
    bindings: ['alt+shift+space']

  # 포커스된 창을 타일링으로 변경.
  - commands: ['toggle-tiling']
    bindings: ['alt+x']

  # 포커스된 창을 전체 화면으로 변경.
  - commands: ['toggle-fullscreen']
    bindings: ['alt+f']

  # 포커스된 창 최소화.
  - commands: ['toggle-minimized']
    bindings: ['alt+g']

  # 포커스된 창 닫기.
  - commands: ['close']
    bindings: ['alt+shift+q']

  # GlazeWM 프로세스를 안전하게 종료합니다.
  - commands: ['wm-exit']
    bindings: ['alt+shift+x']

  # 구성 파일 재평가.
  - commands: ['wm-reload-config']
    bindings: ['alt+shift+r']

  # 모든 창 다시 그리기.
  - commands: ['wm-redraw']
    bindings: ['alt+shift+w']

  # `workspaces` 설정에 정의된 다음/이전 활성 작업 공간에 포커스합니다.
  - commands: ['focus --next-active-workspace']
    bindings: ['alt+s']
  - commands: ['focus --prev-active-workspace']
    bindings: ['alt+a']

  # 마지막으로 포커스했던 작업 공간에 포커스합니다.
  - commands: ['focus --recent-workspace']
    bindings: ['alt+q']

  # `workspaces` 설정에 정의된 작업 공간으로 포커스를 변경합니다.
  - commands: ['focus --workspace B']
    bindings: ['alt+b']
  - commands: ['focus --workspace D']
    bindings: ['alt+d']
  - commands: ['focus --workspace F']
    bindings: ['alt+f']
  - commands: ['focus --workspace I']
    bindings: ['alt+i']
  - commands: ['focus --workspace M']
    bindings: ['alt+m']
  - commands: ['focus --workspace N']
    bindings: ['alt+n']
  - commands: ['focus --workspace T']
    bindings: ['alt+t']
  - commands: ['focus --workspace Z']
    bindings: ['alt+z']

  # 포커스된 창의 부모 작업 공간을 주어진 방향의 모니터로 이동합니다.
  - commands: ['move-workspace --direction left']
    bindings: ['alt+shift+left']
  - commands: ['move-workspace --direction right']
    bindings: ['alt+shift+right']
  - commands: ['move-workspace --direction up']
    bindings: ['alt+shift+up']
  - commands: ['move-workspace --direction down']
    bindings: ['alt+shift+down']

  # 포커스된 창을 `workspaces` 설정에 정의된 작업 공간으로 이동합니다.
  # - commands: ['move --workspace A', 'focus --workspace A']
  #   bindings: ['alt+shift+a']
  - commands: ['move --workspace B', 'focus --workspace B']
    bindings: ['alt+shift+b']
  - commands: ['move --workspace D', 'focus --workspace D']
    bindings: ['alt+shift+d']
  - commands: ['move --workspace F', 'focus --workspace F']
    bindings: ['alt+shift+f']
  - commands: ['move --workspace I', 'focus --workspace I']
    bindings: ['alt+shift+i']
  - commands: ['move --workspace M', 'focus --workspace M']
    bindings: ['alt+shift+m']
  - commands: ['move --workspace N', 'focus --workspace N']
    bindings: ['alt+shift+n']
  - commands: ['move --workspace T', 'focus --workspace T']
    bindings: ['alt+shift+t']
  - commands: ['move --workspace Z', 'focus --workspace Z']
    bindings: ['alt+shift+z']