general:
  # Commands to run when the WM has started. This is useful for running a
  # script or launching another application.
  # Example: The below command launches Zebar.
  startup_commands: ['shell-exec zebar']

  # Commands to run just before the WM is shutdown.
  # Example: The below command kills Zebar.
  shutdown_commands: ['shell-exec taskkill /IM zebar.exe /F']

  # Commands to run after the WM config is reloaded.
  config_reload_commands: []

  # Whether to automatically focus windows underneath the cursor.
  focus_follows_cursor: false

  # Whether to switch back and forth between the previously focused
  # workspace when focusing the current workspace.
  toggle_workspace_on_refocus: false

  cursor_jump:
    # Whether to automatically move the cursor on the specified trigger.
    enabled: true

    # Trigger for cursor jump:
    # - 'monitor_focus': Jump when focus changes between monitors.
    # - 'window_focus': Jump when focus changes between windows.
    trigger: 'window_focus'

  # How windows should be hidden when switching workspaces.
  # - 'cloak': Recommended. Hides windows with no animation.
  # - 'hide': Legacy method (v3.5 and earlier) that has a brief animation,
  # but has stability issues with some apps.
  hide_method: 'cloak'

  # Affects which windows get shown in the native Windows taskbar. Has no
  # effect if `hide_method: 'hide'`.
  # - 'true': Show all windows (regardless of workspace).
  # - 'false': Only show windows from the currently shown workspaces.
  show_all_in_taskbar: false

gaps:
  # Whether to scale the gaps with the DPI of the monitor.
  scale_with_dpi: true

  # Gap between adjacent windows.
  inner_gap: '15px'

  # Gap between windows and the screen edge.
  outer_gap:
    top: '50px'
    right: '15px'
    bottom: '15px'
    left: '15px'

window_effects:
  # Visual effects to apply to the focused window.
  focused_window:
    # Highlight the window with a colored border.
    # ** Exclusive to Windows 11 due to API limitations.
    border:
      enabled: false
      color: '#8dbcff'

    # Remove the title bar from the window's frame. Note that this can
    # cause rendering issues for some applications.
    hide_title_bar:
      enabled: false

    # Change the corner style of the window's frame.
    # ** Exclusive to Windows 11 due to API limitations.
    corner_style:
      enabled: false
      # Allowed values: 'square', 'rounded', 'small_rounded'.
      style: 'square'

    # Change the transparency of the window.
    transparency:
      enabled: false
      # Can be something like '95%' or '0.95' for slightly transparent windows.
      # '0' or '0%' is fully transparent (and, by consequence, unfocusable).
      opacity: '100%'

  # Visual effects to apply to non-focused windows.
  other_windows:
    border:
      enabled: false
      color: '#a1a1a1'
    hide_title_bar:
      enabled: false
    corner_style:
      enabled: false
      style: 'square'
    transparency:
      enabled: true
      opacity: '85%'

window_behavior:
  # New windows are created in this state whenever possible.
  # Allowed values: 'tiling', 'floating'.
  initial_state: 'tiling'

  # Sets the default options for when a new window is created. This also
  # changes the defaults for when the state change commands, like
  # `set-floating`, are used without any flags.
  state_defaults:
    floating:
      # Whether to center floating windows by default.
      centered: false

      # Whether to show floating windows as always on top.
      shown_on_top: false

    fullscreen:
      # Maximize the window if possible. If the window doesn't have a
      # maximize button, then it'll be fullscreen'ed normally instead.
      maximized: true

      # Whether to show fullscreen windows as always on top.
      shown_on_top: false
  
workspaces:
  # - name: 'A' # for AI
  - name: 'B' # for Browser
    display_name: "Browser"
  - name: 'D' # for Document
    display_name: "Document"
  - name: 'E' # for Explorer
    display_name: "Explorer"
  - name: 'I' # for IDE
    display_name: "IDE"
  - name: 'M' # for Messenger
    display_name: "Messenger"
    bind_to_monitor: 1
  - name: 'N' # for Notes
    display_name: "Notes"
  - name: 'T' # for Terminal
    display_name: "Terminal"
    bind_to_monitor: 1
  - name: 'Z' # for Others

window_rules:
  - commands: ['ignore']
    match:
      # Ignores any Zebar windows.
      - window_process: { equals: 'zebar' }

      # Ignores picture-in-picture windows for browsers.
      - window_title: { regex: '[Pp]icture.in.[Pp]icture' }
        window_class: { regex: 'Chrome_WidgetWin_1|MozillaDialogClass' }

      # Ignore rules for various 3rd-party apps.
      - window_process: { equals: 'PowerToys' }
        window_class: { regex: 'HwndWrapper\[PowerToys\.PowerAccent.*?\]' }
      - window_process: { equals: 'PowerToys' }
        window_title: { regex: '.*? - Peek' }
      - window_process: { equals: 'Lively' }
        window_class: { regex: 'HwndWrapper' }
      # Windows 10 시스템 UI 요소 무시
      - window_class: { equals: 'Windows.UI.Core.CoreWindow' }
      - window_class: { equals: 'ApplicationFrameWindow' }
        window_title: { regex: 'Settings|Microsoft Store' }
      # 파일 탐색기 특수 창 무시 (파일 선택 대화상자, 속성 창 등)
      - window_process: { equals: 'explorer' }
        window_title: { regex: '열기|저장|다른 이름으로 저장|속성|Properties|Open|Save|Save As' }
        
      # 카카오톡 알림창 무시
      - window_process: { equals: 'KakaoTalk' }
        window_title: { regex: '알림|Notification|새 메시지|New message' }
      
      # 슬랙 알림창 무시
      - window_process: { equals: 'Slack' }
        window_title: { regex: 'Notification|알림|Slack Notification' }

  - commands: ["set-floating --centered"]
    match:
      - window_process: { equals: 'Taskmgr' }
      - window_process: { equals: "explorer" }
        window_title: { regex: 'Properties|설정|속성|제어판' }
      - window_title: { regex: 'Settings|설정' }

  # Auto-assign windows to workspaces
  - commands: ['move --workspace T', 'focus --workspace T']
    match:
      - window_process: { equals: 'WindowsTerminal' }
      - window_process: { equals: 'cmd' }
      - window_process: { equals: 'powershell' }
      - window_process: { equals: 'wt' }
      
  - commands: ['move --workspace B', 'focus --workspace B']
    match:
      - window_process: { equals: 'chrome' }
      # - window_process: { equals: 'msedge' }
      - window_process: { equals: 'firefox' }
      - window_process: { equals: 'Arc' }
      
  - commands: ['move --workspace I', 'focus --workspace I']
    match:
      - window_process: { equals: 'idea64' }
      - window_process: { equals: 'Code' }
      - window_process: { equals: 'Cursor' }
      - window_process: { equals: 'Trae' }
      - window_process: { equals: 'eclipse' }  # Eclipse IDE 추가
      
  - commands: ['move --workspace N', 'focus --workspace N']
    match:
      - window_process: { equals: 'Obsidian' }
      
  - commands: ['move --workspace E', 'focus --workspace E']
    match:
      - window_process: { equals: 'explorer' }
        window_title: { not_regex: '열기|저장|다른 이름으로 저장|속성|Properties|Open|Save|Save As' }
      
  - commands: ['move --workspace D', 'focus --workspace D']
    match:
      - window_process: { equals: 'EXCEL' }
      - window_process: { equals: 'WINWORD' }
      - window_process: { equals: 'POWERPNT' }

  # 메신저 앱 규칙 (플로팅 모드로 설정하고 M 작업 공간으로 이동)
  - commands: ['set-floating --centered', 'move --workspace M']
    match:
      - window_process: { equals: 'Slack' }
        window_title: { not_regex: 'Notification|알림|Slack Notification' }
      - window_process: { equals: 'KakaoTalk' }
        window_title: { not_regex: '알림|Notification|새 메시지|New message' }
  # 지정되지 않은 모든 앱을 Z 작업 공간으로 이동
  - commands: ['move --workspace Z', 'focus --workspace Z']
    match:
      # 이미 규칙이 있는 앱들은 제외
      - window_process: { not_regex: 'zebar|WindowsTerminal|cmd|powershell|wt|chrome|firefox|Arc|idea64|Code|Cursor|Trae|eclipse|Obsidian|explorer|EXCEL|WINWORD|POWERPNT|Slack|KakaoTalk' }
binding_modes:
  # When enabled, the focused window can be resized via arrow keys or HJKL.
  - name: 'resize'
    keybindings:
      - commands: ['resize --width -2%']
        bindings: ['h', 'left']
      - commands: ['resize --width +2%']
        bindings: ['l', 'right']
      - commands: ['resize --height +2%']
        bindings: ['k', 'up']
      - commands: ['resize --height -2%']
        bindings: ['j', 'down']
      # Press enter/escape to return to default keybindings.
      - commands: ['wm-disable-binding-mode --name resize']
        bindings: ['escape', 'enter']

keybindings:
  # Application launch shortcuts
  - commands: ['shell-exec Arc']
    bindings: ['lalt+lwin+a']
  - commands: ['shell-exec cmd /c "start "" "C:\Program Files (x86)\Kakao\KakaoTalk\KakaoTalk.exe"']
    bindings: ['lalt+lwin+k']
  - commands: ['shell-exec cmd /c "start "" "C:\Users\MZ02-OHYUNBOK\AppData\Local\Microsoft\WindowsApps\Slack.exe"']
    bindings: ['lalt+lwin+s']
  - commands: ['shell-exec cmd /c "start "" "C:\Program Files (x86)\JetBrains\IntelliJ IDEA 2024.3.4.1\bin\idea64.exe""']
    bindings: ['lalt+lwin+i']
  # - commands: ['shell-exec start Cursor']
  #   bindings: ['lalt+lwin+c']
  - commands: ['shell-exec cmd /c "start "" "C:\Users\MZ02-OHYUNBOK\AppData\Local\Programs\Trae\Trae.exe"']
    bindings: ['lalt+lwin+r']
  - commands: ['shell-exec wt']
    bindings: ['lalt+lwin+t']
  - commands: ['shell-exec cmd /c "start "" "C:\Users\MZ02-OHYUNBOK\AppData\Local\Programs\Obsidian\Obsidian.exe"']
    bindings: ['lalt+lwin+o']

  # Shift focus in a given direction.
  - commands: ['focus --direction left']
    bindings: ['alt+h']
  - commands: ['focus --direction right']
    bindings: ['alt+l']
  - commands: ['focus --direction up']
    bindings: ['alt+k']
  - commands: ['focus --direction down']
    bindings: ['alt+j']

  # Move focused window in a given direction.
  - commands: ['move --direction left']
    bindings: ['alt+shift+h']
  - commands: ['move --direction right']
    bindings: ['alt+shift+l']
  - commands: ['move --direction up']
    bindings: ['alt+shift+k']
  - commands: ['move --direction down']
    bindings: ['alt+shift+j']

  # Resize focused window by a percentage or pixel amount.
  - commands: ['resize --width -2%']
    bindings: ['alt+u']
  - commands: ['resize --width +2%']
    bindings: ['alt+p']
  - commands: ['resize --height +2%']
    bindings: ['alt+o']
  - commands: ['resize --height -2%']
    bindings: ['alt+i']

  # As an alternative to the resize keybindings above, resize mode enables
  # resizing via arrow keys or HJKL. The binding mode is defined above with
  # the name 'resize'.
  - commands: ['wm-enable-binding-mode --name resize']
    bindings: ['alt+r']

  # Disables window management and all other keybindings until alt+shift+p
  # is pressed again.
  - commands: ['wm-toggle-pause']
    bindings: ['alt+shift+p']

  # Change tiling direction. This determines where new tiling windows will
  # be inserted.
  - commands: ['toggle-tiling-direction']
    bindings: ['alt+v']

  # Change focus from tiling windows -> floating -> fullscreen.
  # - commands: ['wm-cycle-focus']
  #   bindings: ['alt+space']

  # Change the focused window to be floating.
  - commands: ['toggle-floating --centered']
    bindings: ['alt+shift+space']

  # Change the focused window to be tiling.
  # - commands: ['toggle-tiling']
  #   bindings: ['alt+x']

  # Change the focused window to be fullscreen.
  - commands: ['toggle-fullscreen']
    bindings: ['alt+f']

  # Minimize focused window.
  - commands: ['toggle-minimized']
    bindings: ['alt+g']

  # Close focused window.
  - commands: ['close']
    bindings: ['alt+shift+q']

  # Kill GlazeWM process safely.
  - commands: ['wm-exit']
    bindings: ['alt+shift+e']

  # Re-evaluate configuration file.
  - commands: ['wm-reload-config']
    bindings: ['alt+shift+r']

  # Redraw all windows.
  - commands: ['wm-redraw']
    bindings: ['alt+shift+w']

  # Focus the next/previous active workspace defined in `workspaces` config.
  - commands: ['focus --next-active-workspace']
    bindings: ['alt+s']
  - commands: ['focus --prev-active-workspace']
    bindings: ['alt+a']

  # Focus the workspace that last had focus.
  - commands: ['focus --recent-workspace']
    bindings: ['alt+q']

  # Change focus to a workspace defined in `workspaces` config.
  - commands: ['focus --workspace B']
    bindings: ['alt+b']
  - commands: ['focus --workspace D']
    bindings: ['alt+d']
  - commands: ['focus --workspace E']
    bindings: ['alt+e']
  - commands: ['focus --workspace I']
    bindings: ['alt+i']
  - commands: ['focus --workspace M']
    bindings: ['alt+m']
  - commands: ['focus --workspace N']
    bindings: ['alt+n']
  - commands: ['focus --workspace T']
    bindings: ['alt+t']
  - commands: ['focus --workspace Z']
    bindings: ['alt+z']

  # Move the focused window's parent workspace to a monitor in a given
  # direction.
  - commands: ['move-workspace --direction left']
    bindings: ['alt+shift+left']
  - commands: ['move-workspace --direction right']
    bindings: ['alt+shift+right']
  - commands: ['move-workspace --direction up']
    bindings: ['alt+shift+up']
  - commands: ['move-workspace --direction down']
    bindings: ['alt+shift+down']

  # Move focused window to a workspace defined in `workspaces` config.
  # - commands: ['move --workspace A', 'focus --workspace A']
  #   bindings: ['alt+shift+a']
  - commands: ['move --workspace B', 'focus --workspace B']
    bindings: ['alt+shift+b']
  - commands: ['move --workspace D', 'focus --workspace D']
    bindings: ['alt+shift+d']
  - commands: ['move --workspace E', 'focus --workspace E']
    bindings: ['alt+shift+e']
  - commands: ['move --workspace I', 'focus --workspace I']
    bindings: ['alt+shift+i']
  - commands: ['move --workspace M', 'focus --workspace M']
    bindings: ['alt+shift+m']
  - commands: ['move --workspace N', 'focus --workspace N']
    bindings: ['alt+shift+n']
  - commands: ['move --workspace T', 'focus --workspace T']
    bindings: ['alt+shift+t']
  - commands: ['move --workspace Z', 'focus --workspace Z']
    bindings: ['alt+shift+z']
