#!/bin/sh

BRANCH_NAME=$(git symbolic-ref --short HEAD 2>/dev/null)

if [ -n "$BRANCH_NAME" ] && [ "$2" != "merge" ] && [ "$2" != "squash" ]; then
    # KALIS-숫자 패턴 추출
    ISSUE_NUMBER=$(echo "$BRANCH_NAME" | grep -o 'KALIS-[0-9]\+')

    if [ -n "$ISSUE_NUMBER" ]; then
        PREFIX="[$ISSUE_NUMBER]"

        # 이미 이슈 번호가 포함되어 있는지 확인
        if ! grep -q "$ISSUE_NUMBER" "$1"; then
            sed -i '.bak' "1s/^/$PREFIX /" "$1"
        fi
    fi
fi